services:
  db:
    image: postgres:15
    container_name: fipe_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fipe
      POSTGRES_USER: fipe
      POSTGRES_PASSWORD: Fipe@2024Secure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  bot:
    build: .
    container_name: fipe_bot
    restart: unless-stopped
    depends_on:
      - db
    environment:
      TELEGRAM_TOKEN: "8414017177:AAGEd8N1ECVeewByg4ifcZwSTzUBLU-K5BE"
      DB_HOST: db
      DB_NAME: fipe
      DB_USER: fipe
      DB_PASS: Fipe@2024Secure
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
